/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class PaketWisata_1 extends javax.swing.JFrame {

    /**
     * Creates new form PaketWisata
     */
    public PaketWisata_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBpakettour = new javax.swing.JComboBox<>();
        jtfbiaya = new javax.swing.JTextField();
        jtffas = new javax.swing.JTextField();
        jtfsarana = new javax.swing.JTextField();
        jtfdatang = new javax.swing.JTextField();
        jtfberangkat = new javax.swing.JTextField();
        jtflama = new javax.swing.JTextField();
        jtftujuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfjumlah1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Pilih Paket");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 30, 100, 30);

        jLabel9.setText("Tujuan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 70, 100, 30);

        jCBpakettour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Paket Tour --", "Individual Tour", "Family Group Tour", "Group Tour" }));
        jCBpakettour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBpakettourActionPerformed(evt);
            }
        });
        jPanel1.add(jCBpakettour);
        jCBpakettour.setBounds(200, 30, 170, 30);

        jtfbiaya.setEditable(false);
        jPanel1.add(jtfbiaya);
        jtfbiaya.setBounds(200, 350, 170, 30);

        jtffas.setEditable(false);
        jPanel1.add(jtffas);
        jtffas.setBounds(200, 310, 170, 30);

        jtfsarana.setEditable(false);
        jPanel1.add(jtfsarana);
        jtfsarana.setBounds(200, 270, 170, 30);

        jtfdatang.setEditable(false);
        jPanel1.add(jtfdatang);
        jtfdatang.setBounds(200, 230, 170, 30);

        jtfberangkat.setEditable(false);
        jPanel1.add(jtfberangkat);
        jtfberangkat.setBounds(200, 190, 170, 30);

        jtflama.setEditable(false);
        jPanel1.add(jtflama);
        jtflama.setBounds(200, 150, 170, 30);

        jtftujuan.setEditable(false);
        jPanel1.add(jtftujuan);
        jtftujuan.setBounds(200, 70, 170, 30);

        jLabel7.setText("Biaya");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 350, 60, 20);

        jLabel8.setText("Fasilitas");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 310, 60, 20);

        jLabel2.setText("Sarana");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 270, 60, 20);

        jLabel6.setText("Kedatangan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 230, 70, 30);

        jLabel5.setText("Keberangkatan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 190, 90, 30);

        jLabel4.setText("Lama berwisata");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 150, 90, 30);

        jLabel10.setText("Jumlah Wisatawan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 110, 120, 30);

        jtfjumlah1.setEditable(false);
        jtfjumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfjumlah1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtfjumlah1);
        jtfjumlah1.setBounds(200, 110, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 90, 570, 400);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Destination Packet");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(270, 20, 260, 30);

        jLabel11.setText("Jl. Mayjend. Sungkono 38 - 40, Mangu Harjo, Kota Madiun, Jawa Timur 63129");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 50, 520, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Qoriatul Masfufah\\Downloads\\Gambar\\10555f-raja-ampat-in-high-resolution.jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-220, 0, 1900, 510);

        setBounds(0, 0, 792, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void jCBpakettourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBpakettourActionPerformed
        // TODO add your handling code here:
        
        if(jCBpakettour.getSelectedItem().equals("Individual Tour"))
        {             
            jtftujuan.setText("Raja Ampat, Papua");
            jtfjumlah1.setText("2");
            jtflama.setText("3 Hari");             
            jtfberangkat.setText("Rabu, 1 Feb 2016");             
            jtfdatang.setText("Jumat, 3 Feb 2016");             
            jtfsarana.setText("Garuda Indonesia");             
            jtffas.setText("Snack, makan 3x sehari");             
            jtfbiaya.setText("Rp.50.000.000");                         
        }else if(jCBpakettour.getSelectedItem().equals("Family Group Tour"))
        
        {             
            jtftujuan.setText("Gili, Lombok");
            jtfjumlah1.setText("5");
            jtflama.setText("4 Hari");             
            jtfberangkat.setText("Jumat, 3 Feb 2016");             
            jtfdatang.setText("Selasa, 7 Feb 2016");             
            jtfsarana.setText("Garuda Indonesia, Mobil");             
            jtffas.setText("Snack, Hotel");             
            jtfbiaya.setText("Rp.100.000.000");                         
        }else if(jCBpakettour.getSelectedItem().equals("Group Tour"))
        {
            jtftujuan.setText("Kuta, Bali");
            jtfjumlah1.setText(">10");
            jtflama.setText("4 Hari");             
            jtfberangkat.setText("Kamis, 2 Feb 2016");             
            jtfdatang.setText("Senin, 6 Feb 2016");             
            jtfsarana.setText("Garuda Indonesia, Mobil");             
            jtffas.setText("Snack, Hotel");             
            jtfbiaya.setText("Rp.150.000.000"); 
        }
        
    }//GEN-LAST:event_jCBpakettourActionPerformed

    private void jtfjumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfjumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfjumlah1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaketWisata_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaketWisata_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaketWisata_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaketWisata_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaketWisata_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBpakettour;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfberangkat;
    private javax.swing.JTextField jtfbiaya;
    private javax.swing.JTextField jtfdatang;
    private javax.swing.JTextField jtffas;
    private javax.swing.JTextField jtfjumlah1;
    private javax.swing.JTextField jtflama;
    private javax.swing.JTextField jtfsarana;
    private javax.swing.JTextField jtftujuan;
    // End of variables declaration//GEN-END:variables
}
